Add docs about auto detection of issue tracker
preslavmihaylov/todocheck pull request #64
Opened 2020-09-17 07:28 UTC by mehdy

Closes #58

2020-09-20 12:01 UTC, preslavmihaylov requested changes
Could you also document this in the [Github](https://github.com/preslavmihaylov/todocheck/blob/master/README.md#github) and [Gitlab](https://github.com/preslavmihaylov/todocheck/blob/master/README.md#gitlab) sections?

2020-09-21 17:21 UTC, mehdy commented on README.md
> +For public github/gitlab projects it should detect the issue tracker from your git configuration.
Absolutely :see_no_evil:

2020-09-22 09:47 UTC, preslavmihaylov requested changes
There are still some minor typos & I've also suggested restructuring the `Quickstart` section to be more friendly to first-time readers.

2020-09-22 09:47 UTC, preslavmihaylov commented on README.md
> +To integrate with a public github repository, there's no need to provide a `.todocheck.yaml` explicitly as it can automatically detect the issue tracker based on the git remote address.
gitlab, not github

2020-09-22 09:47 UTC, preslavmihaylov commented on README.md
> +And if you want to explicit, please specify the origin of your repo and the `GITLAB` issue tracker in your `.todocheck.yaml` configuration:
And if you want to **be** explicit

2020-09-22 09:47 UTC, preslavmihaylov commented on README.md
> +And if you want to explicit, please specify the origin of your repo and the `GITHUB` issue tracker in your `.todocheck.yaml` configuration:
Same comments here as for the gitlab part

2020-09-22 09:47 UTC, preslavmihaylov commented on README.md
> +Otherwise you will need a `.todocheck.yaml` configuration file in the root of your project first.
This line assumes some context although it's in the start of the `Quickstart` section. This section will typically be read by newcomers to the tool.

For example, it already mentions an issue tracker when it isn't already mentioned that todocheck needs a way to integrate with one.

I suggest restructuring this part in the following way:
```
First, you need to configure `todocheck`'s integration with your issue tracker.
This is done by creating a `.todocheck.yaml` file in the root of your project.

For public github or gitlab repositories, you need not specify a config file, as long as you are using git, as `todocheck` will interpret your issue tracker from the git configuration.

Alternatively, the explicit configuration for a public github repository would look like this:
(config follows)
```

2020-09-22 17:53 UTC, mehdy commented
> There are still some minor typos & I've also suggested restructuring the `Quickstart` section to be more friendly to first-time readers.

Good points. Thanks! I'll make the changes.

2020-09-24 18:16 UTC, preslavmihaylov approved these changes
All looks good now!

2020-09-24 18:16 UTC, preslavmihaylov commented
Feel free to squash & merge unless you intend to make any more changes.

2020-09-25 12:31 UTC, merged